### PR TITLE
Transformed to OO, logging, auto-detection of modules, single topleve…

### PR DESCRIPTION
**Pull request by TrickMcCarthy**
The original problem that this PR solves is removing the requirement of multiple Terrafiles. One per sub folder per environment(DEV|STAGING|PROD), if you try and have a single Terrafile at the top level it downloads every module every time. 
Using this solution you have one Terrafile at the top level of each environment. You run pterrafile as normal within each subfolder and it only downloads the modules required for that subfolder.
While I was doing the above I took took the opportunity to transform it to OO and add logging.

Its a bit of a break from previous version, a release note would need to be added to explain to existing users the changes they would require to upgrade, but these changes would be reducing all those Terrafiles down to a central one per environment.

If the above is too radical a change I can set up a separate repo with a new name and refer back to this repo as the originator.

### CODE REVIEW

**Comment by raymondbutcher** [comment]
Hi @TrickMcCarthy. I think the filtering logic is a bit too specific to how you use Terraform. Too opinionated as you say. This change would break all of our projects that are using python-terrafile.

When we use python-terrafile (we've stopped using it in some newer projects) we tend to have a single `modules` directory with a `Terrafile` in it. We run `python-terrafile` once and it downloads *all* modules for all stacks/environments for the entire project. Then the various stacks/environments have `source = "../../../modules/some-module"`.

Would that not work for you? The benefit of a single Terrafile is that you only download a module once, even when it's used by many different stacks/environments.

If that doesn't suit, I'd be interested to know more about how your project is structured and why.

As for changing it to object-oriented code... I'm sorry but I see this as a change for the worse, with no actual benefit. I prefer simple functions and generally only use classes when dealing with shared/persistent state or want to expose a particular API.

**Comment by TrickMcCarthy** [comment]
Hi @raymondbutcher ,
Thanks for getting back to me on the PR.  To give some replies to your questions.
Paraphasing here, why not a separate single common module location as the download and thus have single Terrafile?
**Answer:** This doesn't scale in a nice manner, its fine for small focused projects, but I'm involved in large infrastructure platform that supports 10s of small focused projects. Image 10s of subfolders within each environment(DEV,STAGING,QA,PROD,PERF,PREPROD, etc...) focused on particular technical areas such as vpc, security, monitoring, CI etc..., each sub folder containing subfolders that have specific terraform that contains multiple versioned modules.
When you want to apply a change to one of those subfolders, you do not want pterrafile downloading every single module from each subfolder across the whole environment or multiple environments(I would not want to risk stale modules being applied).Thus with current implementation you have a Terrafile at each subfolder level, so it only refreshes the modules you are going to apply. In this PR you only require one Terrafile at the top of each environment that only downloads the modules required in your subfolder. It makes it easy to see what version each of your modules is currently at, so you know what changes to promote across your environments.
In the future when the underlying cloud vendors resources become more defensive in their ability to create and destroy(they need to destroy or create resources quickly), then all terraform will be auto applied. You would not want everything download under those circumstances either.
Hopefully this explains why I believe there is value in my proposed change. 
OO being a change for the worse
**Answer**
It again comes to scaling. Procedural style for python scripts works fine until it doesn't. My opinion on this is its best to switch to OO style earlier than required rather than later. So I agree, it is early to switch, but perhaps not too early, as it will allow more controlled code structure to develop from this point, rather than a decision being made at a later date. I can see that this project may never grow in functionality to warrant the shift.

**Comment by raymondbutcher** [comment]
Hi again @TrickMcCarthy. You're welcome, and likewise thanks for explaining your use case.

If I understand correctly, your goal is to have one Terrafile that is used by multiple stacks, but you want python-terrafile to only download modules which are used by the stack that you're currently working on, to avoid downloading irrelevant modules. You think having a single Terrafile improves visibility of the module versions in that environment, as opposed to having separate Terrafiles in subdirectories. And not mentioned: having multiple Terrafiles could result in downloading modules multiple times if you switch between subdirectories that require the same modules.

Have I got that right? I'd be happy to explore solutions with you that don't break functionality for existing projects. But of course you're free to fork it if you'd prefer.

Regarding OO... I'm afraid we might have to agree to disagree. I don't think OO is required for larger scale or more complex projects. Functions can be moved into separate modules to maintain a sensible structure.

Let's take a look at one of the methods in your PR:

```python
    def _get_repo_name_from_url(self, url: str) -> str:
        logger.debug("url {}".format(url))
        last_suffix_index = url.rfind(".git")
        last_slash_index = url.rfind("/",0,last_suffix_index)
        if last_suffix_index < 0:
            last_suffix_index = len(url)

        if last_slash_index < 0 or last_suffix_index <= last_slash_index:
            raise Exception("Badly formatted url {}".format(url))

        return url[last_slash_index + 1:last_suffix_index]
```

This function doesn't really have anything to do with a Terrafile. It doesn't use `self`. If you wanted to test this, you'd need to create an instance of the Terrafile class and then call this method. Or you could keep it as a function and call it directly. I don't see any reason for this to be part of the Terrafile class.

When using classes, I always use the `@classmethod` and `@staticmethod` decorators. They kind of highlight when you're using a class for API purposes only, as opposed to using a class to represent some kind of entity. In this case, most of your methods would use either of those decorators. The class doesn't really represent anything except the program itself (which I suppose is not necessarily a bad thing, it just seems unnecessary).

**Comment by TrickMcCarthy** [comment]
@raymondbutcher 
In regards to OO,  many procedural projects can scale well, its your repo, so your opinion is the one that counts and it's not something worth getting stuck on. I am willing to remove the OO changes. Thanks for pointing out the classmethod, staticmethod decorators, I will utilize them in future for class methods not requiring self or separate external functionality as the case may present themselves.

So, let's discuss as you offered, how to make an acceptable change to meet the requirements outlined above.
if I add a 'parameter flag/config file needs to exist' to enable the opinionated version, so the default behaviour remains the same and existing projects would not be broken when they upgrade. I do not see that working too well. As its duality that would need to be maintained within the existing project. I think this could only work if the feature was called incubating and became default behaviour on next major version change, perhaps based upon user voting.  I think users accept that they need to make adjustments between major version increments.

If I just detect that the correct name matching between Terrafile module names and Terrafile yaml entries is matching, If even one mismatch occurred assume that the original behaviour is required. Thinking about this solution I do not like it, as its changing behaviour unbeknownst to the user, unless some message appeared asking them to confirm the usage of the new behaviour. Then this would become tiresome, so first option would seem better.

Any other thoughts on how it would be acceptably implemented?

**Comment by raymondbutcher** [comment]
I can see the benefit of this, it does seem useful, but I don't want to force users to change their projects. I think trying to force users to have a specific project structure would push most people away from using this tool. I know I would be less likely to use it.

I think it could be OK to put this behind a command line flag and/or have a reserved key in the Terrafile YAML that enables it. I think it could slot in here quite easily:

https://github.com/claranet/python-terrafile/blob/8c502112b00bebc010f0cd9d463252f2ec3fe7a4/terrafile/__init__.py#L93-L100

```python
def update_modules(path):
    terrafile_path = get_terrafile_path(path)
    module_path = os.path.dirname(terrafile_path)
    module_path_name = os.path.basename(os.path.abspath(module_path))

    terrafile = read_terrafile(terrafile_path)

    if THIS_FEATURE_ENABLED:                                 # this
        found_modules = find_used_modules(os.getcwd())       # this
        terrafile = filter_modules(terrafile, found_modules) # this

    for name, repository_details in sorted(terrafile.items()):
        ...
```

Of course `THIS_FEATURE_ENABLED` would not be the real name, it probably needs to be a function argument rather than a global variable, etc. Maybe you wouldn't use `os.getcwd()` there. This is just a rough example to show how it could be made optional without being much of a maintenance burden.

**Pull request closed without merging**
