### PR TITLE
Addition of opinionated Terrafile support

### PR DESCRIPTION
**Pull request by TrickMcCarthy**
@raymondbutcher I have tried to add the changes in the way you indicated. This change adds opinionated Terrafile format that allows download of just the modules you require to run the terrafiles at sub levels. It also adds logging.

### CODE REVIEW

**Comment by raymondbutcher** [comment]
Hi @TrickMcCarthy . Please remove the logging changes as they are not required for this feature. Fundamentally changing how the program outputs information would require some discussion before it would be accepted. Basically, I like how the current output is clean and simple. If you need more verbose output, it will need to be done in a separate pull request and should probably be enabled by a CLI argument or environment variable.

In your example:

```
├── dev
│   ├── apps
│   │   └── main.tf
│   ├── ec2
│   │   └── main.tf
│   ├── security
│   │   └── main.tf
│   ├── Terrafile
│   └── vpc
│       └── main.tf
```

When you run `cd dev/apps ; pterrafile --terrafile ../Terrafile --optimizedownloads True`  does it download the modules into `dev/<module-name>` next to `Terrafile`? Doesn't that pollute your `dev` directory with a bunch of fetched modules that can change over time? We tend to put `Terrafile` in a dedicated `modules` directory to keep them separate and out of the way (can use `.gitignore` to ignore all subdirectories, can delete all subdirectories, because they're all managed by `Terrafile`).

**Comment by TrickMcCarthy** [comment]
I will remove the logging and make another submission.
In the example structure:
It downloads the modules to the source location you have specified in your terraform main.tf file. It auto parses your terraform files and retrieves the module name and the associated source target location. Then looks up the module name as a key in the central Terrafile. Clones/Copies the repo from the source value in your terrafile to the source location given in your main.tf file. 
It expects that you module name is a key in your Terrafile and your source attribute in your terraform files contain a target path location to where you want the module code downloaded to and that path contains the git repo name within it ( to cover special case where people use a git repo with subfolders instead of different git repos).
See below, You run the pterrafile command from /dev/apps/ folder and example.git repo would be cloned into cwd relative path modules/example thus ending up in dev/apps/modules/example
#main.tf located in apps
module "example" {
source = "modules/example/subfolder1"
}
#Terrafile located in DEV
example:
    source: "https://github.com/joeblogs/example.git"
    version: "master"

**Comment by TrickMcCarthy** [comment]
@raymondbutcher I have reverted the logging back to print statements and I have updated the README.md to make it clearer regarding the above PR discussion.

**Comment by TrickMcCarthy** [comment]
Closing this for now, there is an issue I want to fix first.

**Pull request closed without merging**
